@startuml Rolling Deployment
skinparam backgroundcolor transparent

left to right direction

actor Users
agent Proxy

rectangle "v1.0" as V1 {
    card B1 #CornflowerBlue
    card B2 #CornflowerBlue
    card B3 #CornflowerBlue

    [B1] -[hidden]-> [B2]
    [B2] -[hidden]-> [B3]
}

rectangle "v2.0" as V2 {
    rectangle " " as V2B1 {
        card G1 as 1G1 #LightGreen
        card B2 as 1B2 #CornflowerBlue
        card B3 as 1B3 #CornflowerBlue

        [1G1] -[hidden]-> [1B2]
        [1B2] -[hidden]-> [1B3]
    }

    rectangle " " as V2B2 {
        card G1 as 2G1 #LightGreen
        card G2 as 2G2 #LightGreen
        card B3 as 2B3 #CornflowerBlue

        [2G1] -[hidden]-> [2G2]
        [2G2] -[hidden]-> [2B3]
    }

    rectangle " " as V2B3 {
        card G1 as 3G1 #LightGreen
        card G2 as 3G2 #LightGreen
        card G3 as 3G3 #LightGreen

        [3G1] -[hidden]-> [3G2]
        [3G2] -[hidden]-> [3G3]
    }

    V2B1 ----> V2B2
    V2B2 ----> V2B3
}

Users --> Proxy
Proxy -----> V1 : before deployment
Proxy ---> V2 : phased deployment
@enduml